In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import epanet as epa
import epamodule as em
import seaborn as sns
from scipy import optimize

In [2]:
links = ["../../networks/b-town/nodes", 
         "../../networks/b-town/links", 
         "../../networks/b-town/rede.inp", 
         "../../networks/b-town/3dim.csv"]

In [3]:
group_links = [[1,2,14,13,12,11,10,9,20],[15,16,17,18,19],[4,3,5,6,7,8]]
# 2 => [15, 16, 17, 18, 19]
# 3 => [4, 3, 5, 6, 7, 8]
# 1 => [1, 2, 14, 13, 12, 11, 10, 9, 20]

In [4]:
t = np.array([0.01, 0.079,0.115])
bound = [0.001,0.2]

In [5]:
net = epa.Rede(links, group_links, t, bound)

Começando simulação


# Usando SciPy

In [6]:
net.target -0.001

array([0.009, 0.078, 0.114])

In [7]:
b = optimize.Bounds(0.001,0.2)

In [8]:
b

Bounds(0.001, 0.2)

In [26]:
x0 = np.random.random((100,3))*0.2 +0.001

In [27]:
o = optimize.minimize(net.objetivo, x0[51,:], method='Nelder-Mead')

In [28]:
o

 final_simplex: (array([[0.01000425, 0.0789728 , 0.11497502],
       [0.00998814, 0.07903412, 0.11504173],
       [0.01000858, 0.07889832, 0.11497824],
       [0.0100141 , 0.07897175, 0.11494949]]), array([2.22644303e-09, 4.50017978e-09, 5.15865395e-09, 8.12360668e-09]))
           fun: 2.2264430299672334e-09
       message: 'Optimization terminated successfully.'
          nfev: 141
           nit: 80
        status: 0
       success: True
             x: array([0.01000425, 0.0789728 , 0.11497502])

In [29]:
np.round(o.x, decimals=3)

array([0.01 , 0.079, 0.115])

In [34]:
dc = []
c = 0
for i in range(100):
    try:
        o = optimize.minimize(net.objetivo, x0[i,:], method='Nelder-Mead')
        dc.append(np.round(o.x,decimals=3))
    except:
        c+=1


In [35]:
i/100

0.99

In [36]:
dc

[array([0.01 , 0.079, 0.115]),
 array([ 0.021, -0.308,  0.086]),
 array([0.01 , 0.079, 0.115]),
 array([0.01 , 0.079, 0.115]),
 array([-0.037,  0.14 ,  0.147]),
 array([0.01 , 0.079, 0.115]),
 array([0.01 , 0.079, 0.115]),
 array([-0.005,  3.386,  0.143]),
 array([0.01 , 0.079, 0.115]),
 array([ 0.021, -5.57 ,  0.086]),
 array([0.01 , 0.079, 0.115]),
 array([-0.049,  0.293,  0.143]),
 array([-0.036,  0.094,  0.221]),
 array([0.01 , 0.079, 0.115]),
 array([0.01 , 0.079, 0.115]),
 array([ 0.021, -0.09 ,  0.086]),
 array([-0.   ,  2.155,  0.143]),
 array([0.01 , 0.079, 0.115]),
 array([0.01 , 0.079, 0.115]),
 array([0.01 , 0.079, 0.115]),
 array([0.01 , 0.079, 0.115]),
 array([ 0.021, -0.051,  0.086]),
 array([0.01 , 0.079, 0.115]),
 array([-0.008,  0.282,  0.143]),
 array([-0.128,  0.294,  0.143]),
 array([-4.377,  0.14 ,  0.147]),
 array([0.01 , 0.079, 0.115]),
 array([0.01 , 0.079, 0.115]),
 array([0.   , 0.298, 0.143]),
 array([0.01 , 0.079, 0.115]),
 array([0.01 , 0.079, 0.115]),
 ar

# Calculando Centroide

In [ ]:
net.gradient(t)

In [ ]:
sum(net.gradient(t))

In [ ]:
net.target

In [ ]:
x,y,z = np.mgrid[0.002:0.2:0.001,0.002:0.2:0.001,0.002:0.2:0.001]
xyz = np.vstack((x.flatten(), y.flatten(), z.flatten())).T
xyz

In [ ]:
xyz.shape

In [ ]:
res = np.zeros((xyz.shape[0],))
res

In [ ]:
for i in range(xyz.shape[0]):
    res[i] += abs(sum(net.gradient(xyz[i,:])))
    net.restart()

In [ ]:
plt.plot(res)

In [ ]:
interacoes = 100
lr = 0.001
dim = 3
x0 = np.array([0.002,0.1,0.100])
x = np.zeros((interacoes,dim))
x[0,:] = x0
y = np.zeros((interacoes,))
y[0] = net.objetivo(x0)
for i in range(1,interacoes):
    x[i,:] += x[i-1,:] - lr*net.gradient(x[i-1,:])
    y[i] += net.objetivo(x[i,:]) 

In [ ]:
plt.plot(y)

In [ ]:
min(y)

In [ ]:
lr = 0.001
dim = 3
x0 = np.array([0.002,0.1,0.100])
x = x0
y = [net.objetivo(x0)]de
i = 0
values = [x0]
while sum(abs(net.gradient(x)) > 0.1):
    x -= lr*net.gradient(x)    
    y.append(net.objetivo(x)) 
    values.append(x)
    i+=1
    if i > 200:
        break

In [ ]:
plt.plot(y[:90:])

In [ ]:
values[y.index(min(y))]

In [ ]:
bool(sum(x > 0))

# Fazendo a função para aplicar em múltiplos pontos iniciais

In [ ]:
a = np.array([1,-2,3])
f = lambda x: -1 if x < 0 else 1
np.vectorize(f)(a)

In [ ]:
def grad_steps(x0, lr=0.001, max_interacoes=400):
    try:
        dim = len(x0)
        x = x0
        y = [net.objetivo(x0)]
        caminho = [net.get_dist(x0)]
        i = 0
        values = [x0]
        while np.sqrt(sum(net.gradient(x)**2))>0:
            increment = np.vectorize(lambda x: 1 if x>0 else -1)
            g = increment(net.gradient(x))
            x -= lr*g
            caminho.append(net.get_dist(x))
            y.append(net.objetivo(x)) 
            values.append(x)
            i+=1
            if i > max_interacoes:
                print("Excedeu as interações limite")
                break
            if sum(x<0):
                print("Escapou do intervalo de confiança")
                break
    finally:
        net.restart()
        return values, y, caminho

In [ ]:
net.gradient(net.target)

In [ ]:
x0 = np.round(np.random.random(3)*0.2 +0.001, decimals=3)
#x0 = np.array([0.09435675, 0.18852395, 0.14145076])
x0

In [ ]:
net.get_dist(x0)

In [ ]:
x, y, caminho = grad_steps(x0, lr=0.001)

In [ ]:
plt.plot(y)
plt.yscale('log')

In [ ]:
y[150:160]

In [ ]:
net.gradient(x[0])

In [ ]:
net.objetivo(x[2])

In [ ]:
plt.plot(caminho[150:200])
plt.yscale('log')

In [ ]:
caminho[150:160]

In [ ]:
net.get_dist(x)

In [ ]:
net.objetivo(x)

In [ ]:
net.gradient(x)

In [ ]:
net.get_dist(x)

In [ ]:
x, y = grad_steps(x0, max_interacoes=400)

In [ ]:
plt.plot(y)

In [ ]:
x

In [ ]:
net.restart()

# Gerando os números aleatórios

In [ ]:
#values = np.random.random((100,3))*0.2 +0.001

In [ ]:
# arq = open("teste1.txt", 'w')
# np.savetxt(arq, values)
# arq.close()

In [ ]:
arq = open("teste1.txt")
values = np.loadtxt(arq)
arq.close()

In [ ]:
net.restart()

In [ ]:
pontos = []
pontos_y = []
for i in range(values.shape[0]):
    try:
        x, y = grad_steps(values[i,:])
        pontos.append(x)
        pontos_y.append(net.objetivo(x))
        print(i, x)
        print()
    except:
        continue

In [ ]:
pontos = np.array(pontos)
pontos_y = np.array(pontos_y)

In [ ]:
# arq = open("teste1/result.txt", 'w')
# np.savetxt(arq, pontos)
# arq.close()

In [ ]:
arq = open("teste1/result.txt")
pontos = np.loadtxt(arq)
pontos

In [ ]:
plt.plot(pontos_y)

In [ ]:
pontos_y.mean()

In [ ]:
plt.plot(pontos_y[np.where(pontos_y<=pontos_y.mean())])

In [ ]:
indices = np.where(pontos_y<=pontos_y.mean())

# Calculando Centróide dos pontos resultantes

## Centróide:

In [ ]:
def calc_centroide(vetor_pontos):
    tamanho = vetor_pontos.shape[0]
    v = []
    for i in range(vetor_pontos.shape[1]):
        v.append(vetor_pontos[:,i].sum()/tamanho)
    return v
    

In [ ]:
v = calc_centroide(pontos)

In [ ]:
v

In [ ]:
net.target

### Calculando Centróide dos pontos abaixo da média

In [ ]:
calc_centroide(pontos[indices])

## Distancia do Centróide ao ponto Target

In [ ]:
net.get_dist(v) # isso tem que tender a 0

In [ ]:
net.get_dist(calc_centroide(pontos[indices]))

# Gerando uma quantidade maior de pontos - Teste 2

In [ ]:
# values = np.random.random((500,3))*0.2 +0.001

In [ ]:
# arq = open("teste2/teste2.txt", 'w')
# np.savetxt(arq, values)
# arq.close()

In [ ]:
arq = open("teste2/teste2.txt")
values = np.loadtxt(arq)
arq.close()

In [ ]:
net.restart()

In [ ]:
pontos = []
pontos_y = []
for i in range(values.shape[0]):
    try:
        x, y = grad_steps(values[i,:])
        pontos.append(x)
        pontos_y.append(net.objetivo(x))
        print(i, x)
        print()
    except:
        continue

In [ ]:
pontos = np.array(pontos)
pontos_y = np.array(pontos_y)

In [ ]:
#arq = open("teste2/result.txt", 'w')
#np.savetxt(arq, pontos)
#arq.close()

In [ ]:
arq = open("teste2/result.txt")
pontos = np.loadtxt(arq)

In [ ]:
v = calc_centroide(pontos)

In [ ]:
net.get_dist(v) # isso tem que tender a 0

In [ ]:
pontos[:,0]

In [ ]:
sns.boxplot(pontos[:,1])

In [ ]:
sns.displot(pontos[:,1])

In [ ]:
df = pd.DataFrame(pontos, columns=['g1', 'g2', 'g3'])

In [ ]:
df

In [ ]:
df.median()

In [ ]:
net.get_dist(df.median())

In [ ]:
net.get_dist(df.mean())

In [ ]:
sns.violinplot(df['g1'])

In [ ]:
sns.violinplot(df['g2'])

In [ ]:
sns.violinplot(df['g3'])

In [ ]:
df.describe()